#!/usr/bin/env bash

seekascan()
{
   local n=$#
   local value=${!n}

array=("${@:1}")
echo "${array[@]}"
echo "tamanho: $n"
echo "search : $value"
echo "search: ${!n}"
declare -p array

   for ((i=1;i < $#;i++)) {
      if [ "${!i}" == "${value}" ]; then
         echo $i
         return 0
      fi
   }
   return 1
}

arr=({a..z})
search=v
seekascan "${arr[@]}" $search
exit

if value=$(seekascan "${arr[@]}" $search); then
	echo $value
else
	echo não encontrado
fi

